apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  - Egress
  ingress: [] # deny all
  egress: # allow only to postgres
  - to:
    - ipBlock:
        cidr: "{{ printf \"%s/32\" .Values.postgresIp }}" 
    ports:
    - protocol: TCP
      port: 5432
