apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.name }}-postgres-secret
type: Opaque
data:
  postgres-ip: |-
    {{ .Values.postgresIp | b64enc }}
  postgres-password.yaml: |-
    {{ .Values.postgresPassword | b64enc }}
