apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.Name }}-postgres-secret
  namespace: {{ .Values.Namepsace }}
type: Opaque
data:
  postgres-ip: |-
    {{ .Files.Get "files/postgres-ip" | b64enc }}
  postgres-password.yaml: |-
    {{ .Files.Get "files/postgres-password.yaml" | b64enc }}
