apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.Name }}-users-secret
  namespace: {{ .Values.Namepsace }}
type: Opaque
data:
  falco-db-users.yaml: |-
    {{ .Files.Get "files/falco-db-users.yaml" | b64enc | indent 4 }}
